### ISSUE TITLE
Morning session code review

### ISSUE THREAD

**Issue by gemmen29** [gemmen29/Portfolio#11]

**Comment by akucintavalent** [comment]
Great job @gemmen29 ! Your site looks almost just like the original template. Although I would suggest making your contact form input fields a bit more narrow.

**Comment by Omar-Muhamad** [comment]
Hi @gemmen29,
You did great work actually building this site.😎
and I have some suggestions for you:

- [ ] the width of nav-bar I think it's a little bit bigger 72px I think.
- [ ] The work cards are not centered in my preview and I think it needs more height for each card.

That's it keep the good work😊.

**Comment by ShadyShawkat** [comment]
Hi @gemmen29, 👋🏻 
You have done great thus far. Your work is really clean and it looks really similar to the original Figma design. I do have some suggestions tho :

- [ ] In the header where it says "I’m George Glad to see you!", you can put a `<br>` tag to break the heading text onto two lines -like in the Figma template.
- [ ] A `<header>` tag should contain things like heading text, navs, or simple forms like a search bar. In your "about me" section you have used a header tag. I think you are off better using a `<div>` tag.

That's it for my recommendations. Keep up the good work. 👍🏻

**Comment by gemmen29** [comment]
Thank you all for this feedback
