### ISSUE TITLE
Morning code review

### ISSUE THREAD

**Issue by Hombre2014** [gemmen29/Portfolio#6]
Very nice and clean code both HTML and CSS.
There are some suggestions for changes as follow:
1. Fix the footer background image in the Contact section
2. Rename the headline section with your name and the title of the document.
3. Buttons See Project and Get my Resume needs styling on hover and click.
4. About Myself section is about 40% of the length of the whole width.
5. Make the links in the menu works.

Keep rocking 🚀

**Comment by gemmen29** [comment]
Done.
